a = input("Enter a number for a: ")  
print(type(a))  # This will print <class 'str'> because input() returns a string
b = input("Enter a number for b: ")
print(type(b))  # This will also print <class 'str'>
c = a + b
print("The sum of a and b is:", c)
#because they are of the string type, thats why the output will be concatenated instead of summed.
#to fix this we need type casting.

#in bool T is 1 and F is 0.
a=10
b=20
c=a<b
print(c)  # This will print True because 10 is less than 20
print(type(c))  # This will print <class 'bool'> because c is a boolean value   

print(True+1)
print(True+21)

#complex - real and imaginary parts
a=10
b=20
c=complex(a,b)
print(c)  # This will print (10+20j) because c is a complex number with real part 10 and imaginary part 20
#we can add two complex numbers
#we use in matplotlib and numpy for complex numbers.
a= 1+2j
b= 2+3j
c= a + b

# Sequence data types

# Strings - sequence of characters enclosed in quotes
# can be created by using '' or "" or ''' ''' or """ """
# can be represeented by str
# use double, so that while using the Appostofie, it will be easy to use.
#string is immutable, so we cannot change the value of a string once it is created.
print(dir(str))  # This will print all the methods available for string objects
help(str)  # This will print the documentation for the str class, including its methods and attributes

# Lists - ordered collection of elements, enclosed in square brackets []
# Duplicate elements are allowed in lists, and they can be of different data types.
# It is mutable, so we can change the value of a list after it is created.
print(dir(list))  # This will print all the methods available for list objects

# tuples - ordered collection of elements, enclosed in parentheses ()
# Duplicate elements are allowed in tuples, and they can be of different data types.
# They are immutable, so we cannot change the value of a tuple after it is created.
# Tuples cant be generated with single value, it will be considered as str or int
# to generate with single value, we need to add a comma after the value.
# we can generate the tuple with without the brackets also
print(dir(tuple))  # This will print all the methods available for tuple objects

#sets - unordered collection of unique items enclosed in curly braces {}
# no duplicates are allowed
# different data types are allowed
# set is mutable, so we can change the value of a set after it is created.
# to create an empty set, we need to use set() function, because {} will create an empty dictionary.
print(dir(set))  # This will print all the methods available for set objects

#dict dictionaries - unordered collection of key-value pairs enclosed in curly braces {}
# each item in a dictionary is a key-value pair, where the key is unique and the value can be of any data type.
# keys are immutable, so we cannot change the value of a key after it is created.
# values are mutable, so we can change the value of a value after it is created.
# keys and values can be of different data types.
# keys must be unique, but values can be duplicated.
# we can used for mapping, where we can map a key to a value.
print(dir(dict))  # This will print all the methods available for dictionary objects

#range - sequence of numbers generated by using range() function
# it is immutable, so we cannot change the value of a range after it is created.
# by default range will start from 0 and will increment by 1, but we can specify the start, stop and step values.
# range() function is used in for loops to iterate over a sequence of numbers.
# we can mention start and stop value, but step value is optional, by default it will be 1.
print(dir(range))  # This will print all the methods available for range objects

#bytes - immutable sequence of bytes
print(dir(bytes))  # This will print all the methods available for bytes objects
#bytearray - mutable sequence of bytes
print(dir(bytearray))  # This will print all the methods available for bytearray objects
#frozenset - immutable collection of unique items
print(dir(frozenset))  # This will print all the methods available for frozenset objects

#immutable
#mutable 